language: node_js

node_js:
  - 16

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - mah.siewchun@stengg.com
    on_success: always
    on_failure: always
branches:
  only:
   - development
before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href https://JosephineMah.github.io/bitcoin-order-app/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: dist/bitcoin
  edge: true
  on:
    branch: development

