language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - mah.siewchun@stengg.com
    on_success: always
    on_failure: always
branches:
  only:
   - development
before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href https://<your github username>.github.io/bitcoin-order-app/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: dist/bitcoin
  edge: true
  on:
    branch: development

